version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=errandbuddy
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3307:3306"  # Host:Container
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
